### ISSUE TITLE
想用在openwrt上构建web服务,但是内存占用过高

### ISSUE THREAD

**Issue by Revolution1** [oneoo/alilua#30]
内存会占用到22M左右, 求问有什么办法能降低内存占用么.
因为路由器的ram实在是捉襟见肘(64m)

**Comment by oneoo** [comment]
这个可以限制开启的Lua VM数量，如启动命令行加参数 thread=10

**Comment by Revolution1** [comment]
thread设置成10和1都试过了, 内存占用没什么变化.  还是在21.7m左右, 这是刚 
运行时的内存占用, 没有http请求. 分别在自己的笔记本和vps上测试的.

在 2015年08月27日 13:26, oneoo 写道:

**Comment by oneoo** [comment]
这个共享内存申请大小的代码有BUG，已修正。请在启动的时候加参数 cache-size=1m 控制
可以做到启动为9mb内存占用的样子
